openapi: 3.0.0
info:
  title: Connectivity Ranking API
  version: 1.0.0
paths:
  /lightning/nodes/rankings/isp/{number}:
    get:
      summary: Get rankings of Lightning Network nodes by ISP
      description: Retrieve a list of Lightning Network nodes ranked by their ISP, along with relevant details.
      parameters:
        - in: path
          name: number
          required: true
          schema:
            type: integer
          description: The number to be used in the path.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  isp:
                    type: string
                    description: The Internet Service Provider (ISP) hosting the API.
                  nodes:
                    type: array
                    items:
                      $ref: "#/components/schemas/ConnectivityNode"

components:
  schemas:
    ConnectivityNode:
      type: object
      properties:
        publicKey:
          type: string
          description: The public key identifying the Lightning Network node.
        alias:
          type: string
          description: A human-readable alias for the node.
        capacity:
          type: integer
          description: The total capacity of the node in satoshis.
        channels:
          type: integer
          description: The number of channels the node has open.
        firstSeen:
          type: integer
          description: The timestamp when the node was first seen.
        updatedAt:
          type: integer
          description: The timestamp when the node's information was last updated.
        city:
          type: string
          description: The city where the node is located, if available.
        country:
          type: object
          properties:
            de:
              type: string
            en:
              type: string
            es:
              type: string
            fr:
              type: string
            ja:
              type: string
            pt-BR:
              type: string
            ru:
              type: string
            zh-CN:
              type: string
          description: The country where the node is located, with translations.
        iso_code:
          type: string
          description: The ISO code of the country where the node is located.
        subdivision:
          type: string
          description: The subdivision (e.g., state or province) where the node is located, if available.
